<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Departeman extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Departeman_model');
    } 

    /*
     * Listing of departemen
     */
    function index()
    {
        $data['departemen'] = $this->Departeman_model->get_all_departemen();
		$data['title'] = "List Departemen";
		$data['page']="departemen";
		$this->renderAdmin($data);
    }

    /*
     * Adding a new departeman
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'dep_id' => $this->input->post('dep_id'),
				'nama' => $this->input->post('nama'),
            );
            
            $departeman_id = $this->Departeman_model->add_departeman($params);
            redirect('departeman/index');
        }
        else
        {            
            $data['_view'] = 'departeman/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a departeman
     */
    function edit($id_departemen)
    {   
        // check if the departeman exists before trying to edit it
        $data['departeman'] = $this->Departeman_model->get_departeman($id_departemen);
        
        if(isset($data['departeman']['id_departemen']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'dep_id' => $this->input->post('dep_id'),
					'nama' => $this->input->post('nama'),
                );

                $this->Departeman_model->update_departeman($id_departemen,$params);            
                redirect('departeman/index');
            }
            else
            {
                $data['_view'] = 'departeman/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The departeman you are trying to edit does not exist.');
    } 

    /*
     * Deleting departeman
     */
    function remove($id_departemen)
    {
        $departeman = $this->Departeman_model->get_departeman($id_departemen);

        // check if the departeman exists before trying to delete it
        if(isset($departeman['id_departemen']))
        {
            $this->Departeman_model->delete_departeman($id_departemen);
            redirect('departeman/index');
        }
        else
            show_error('The departeman you are trying to delete does not exist.');
    }
    
    public function renderAdmin($data){
        $this->load->view('layouts/header', $data); 
        $this->load->view('layouts/sidebar' );
        $this->load->view('layouts/maincontent');
        $this->load->view('layouts/footer');
      }

}
