<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jabatan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jabatan_model');
    } 

    /*
     * Listing of jabatan
     */
    function index()
    {
        $data['jabatan'] = $this->Jabatan_model->get_all_jabatan();
        $data['title'] = "List Jabatan";
		$data['page']="jabatan";
		$this->renderAdmin($data);
       
    }

    /*
     * Adding a new jabatan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'kd_jbtn' => $this->input->post('kd_jbtn'),
				'nm_jbtn' => $this->input->post('nm_jbtn'),
            );
            
            $jabatan_id = $this->Jabatan_model->add_jabatan($params);
            redirect('jabatan/index');
        }
        else
        {            
            $data['_view'] = 'jabatan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jabatan
     */
    function edit($id_jabatan)
    {   
        // check if the jabatan exists before trying to edit it
        $data['jabatan'] = $this->Jabatan_model->get_jabatan($id_jabatan);
        
        if(isset($data['jabatan']['id_jabatan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'kd_jbtn' => $this->input->post('kd_jbtn'),
					'nm_jbtn' => $this->input->post('nm_jbtn'),
                );

                $this->Jabatan_model->update_jabatan($id_jabatan,$params);            
                redirect('jabatan/index');
            }
            else
            {
                $data['_view'] = 'jabatan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jabatan you are trying to edit does not exist.');
    } 

    /*
     * Deleting jabatan
     */
    function remove($id_jabatan)
    {
        $jabatan = $this->Jabatan_model->get_jabatan($id_jabatan);

        // check if the jabatan exists before trying to delete it
        if(isset($jabatan['id_jabatan']))
        {
            $this->Jabatan_model->delete_jabatan($id_jabatan);
            redirect('jabatan/index');
        }
        else
            show_error('The jabatan you are trying to delete does not exist.');
    }

    public function renderAdmin($data){
        $this->load->view('layouts/header', $data); 
        $this->load->view('layouts/sidebar' );
        $this->load->view('layouts/maincontent');
        $this->load->view('layouts/footer');
      }
    
}
