<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jnj_jabatan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jnj_jabatan_model');
    } 

    /*
     * Listing of jnj_jabatan
     */
    function index()
    {
        $data['jnj_jabatan'] = $this->Jnj_jabatan_model->get_all_jnj_jabatan();
        
        $data['_view'] = 'jnj_jabatan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jnj_jabatan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'kode' => $this->input->post('kode'),
				'nama' => $this->input->post('nama'),
				'tnj' => $this->input->post('tnj'),
            );
            
            $jnj_jabatan_id = $this->Jnj_jabatan_model->add_jnj_jabatan($params);
            redirect('jnj_jabatan/index');
        }
        else
        {            
            $data['_view'] = 'jnj_jabatan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jnj_jabatan
     */
    function edit($id_jenjangjbtn)
    {   
        // check if the jnj_jabatan exists before trying to edit it
        $data['jnj_jabatan'] = $this->Jnj_jabatan_model->get_jnj_jabatan($id_jenjangjbtn);
        
        if(isset($data['jnj_jabatan']['id_jenjangjbtn']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'kode' => $this->input->post('kode'),
					'nama' => $this->input->post('nama'),
					'tnj' => $this->input->post('tnj'),
                );

                $this->Jnj_jabatan_model->update_jnj_jabatan($id_jenjangjbtn,$params);            
                redirect('jnj_jabatan/index');
            }
            else
            {
                $data['_view'] = 'jnj_jabatan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jnj_jabatan you are trying to edit does not exist.');
    } 

    /*
     * Deleting jnj_jabatan
     */
    function remove($id_jenjangjbtn)
    {
        $jnj_jabatan = $this->Jnj_jabatan_model->get_jnj_jabatan($id_jenjangjbtn);

        // check if the jnj_jabatan exists before trying to delete it
        if(isset($jnj_jabatan['id_jenjangjbtn']))
        {
            $this->Jnj_jabatan_model->delete_jnj_jabatan($id_jenjangjbtn);
            redirect('jnj_jabatan/index');
        }
        else
            show_error('The jnj_jabatan you are trying to delete does not exist.');
    }
    
}
