<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pegawai extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pegawai_model');
    } 

    /*
     * Listing of pegawai
     */
    function index()
    {
        $data['pegawai'] = $this->Pegawai_model->get_all_pegawai();
		$data['title'] = "List Data Pegawai";
		$data['page']="pegawai";
		$this->renderAdmin($data);
    }

    /*
     * Adding a new pegawai
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_jbtn' => $this->input->post('id_jbtn'),
				'id_jnj_jabatan' => $this->input->post('id_jnj_jabatan'),
				'id_departemen' => $this->input->post('id_departemen'),
				'id_bidang' => $this->input->post('id_bidang'),
				'id_stts_wp' => $this->input->post('id_stts_wp'),
				'id_stts_kerja' => $this->input->post('id_stts_kerja'),
				'id' => $this->input->post('id'),
				'nik' => $this->input->post('nik'),
				'nama' => $this->input->post('nama'),
				'jk' => $this->input->post('jk'),
				'npwp' => $this->input->post('npwp'),
				'pendidikan' => $this->input->post('pendidikan'),
				'gapok' => $this->input->post('gapok'),
				'tmp_lahir' => $this->input->post('tmp_lahir'),
				'tgl_lahir' => $this->input->post('tgl_lahir'),
				'alamat' => $this->input->post('alamat'),
				'kota' => $this->input->post('kota'),
				'mulai_kerja' => $this->input->post('mulai_kerja'),
				'ms_kerja' => $this->input->post('ms_kerja'),
				'indexins' => $this->input->post('indexins'),
				'bpd' => $this->input->post('bpd'),
				'rekening' => $this->input->post('rekening'),
				'stts_aktif' => $this->input->post('stts_aktif'),
				'wajibmasuk' => $this->input->post('wajibmasuk'),
				'pengurang' => $this->input->post('pengurang'),
				'indek' => $this->input->post('indek'),
				'mulai_kontrak' => $this->input->post('mulai_kontrak'),
				'cuti_diambil' => $this->input->post('cuti_diambil'),
				'dankes' => $this->input->post('dankes'),
				'photo' => $this->input->post('photo'),
				'no_ktp' => $this->input->post('no_ktp'),
            );
            
            $pegawai_id = $this->Pegawai_model->add_pegawai($params);
            redirect('pegawai/index');
        }
        else
        {
			$this->load->model('Jabatan_model');
			$data['all_jabatan'] = $this->Jabatan_model->get_all_jabatan();

			$this->load->model('Jnj_jabatan_model');
			$data['all_jnj_jabatan'] = $this->Jnj_jabatan_model->get_all_jnj_jabatan();

			$this->load->model('Departeman_model');
			$data['all_departemen'] = $this->Departeman_model->get_all_departemen();

			$this->load->model('Bidang_model');
			$data['all_bidang'] = $this->Bidang_model->get_all_bidang();

			$this->load->model('Stts_wp_model');
			$data['all_stts_wp'] = $this->Stts_wp_model->get_all_stts_wp();
			
			$this->load->model('Stts_kerja_model');
			$data['all_stts_kerja'] = $this->Stts_kerja_model->get_all_stts_kerja();

			$data['_view'] = 'pegawai/add';
			
			$data['title']="Input Data Pegawai";
			$data['page']="inputpegawai";
			$this->renderAdmin($data);
        }
    }  

    /*
     * Editing a pegawai
     */
    function edit($id_pegawai)
    {   
        // check if the pegawai exists before trying to edit it
        $data['pegawai'] = $this->Pegawai_model->get_pegawai($id_pegawai);
        
        if(isset($data['pegawai']['id_pegawai']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_jbtn' => $this->input->post('id_jbtn'),
					'id_jnj_jabatan' => $this->input->post('id_jnj_jabatan'),
					'id_departemen' => $this->input->post('id_departemen'),
					'id_bidang' => $this->input->post('id_bidang'),
					'id_stts_wp' => $this->input->post('id_stts_wp'),
					'id_stts_kerja' => $this->input->post('id_stts_kerja'),
					'id' => $this->input->post('id'),
					'nik' => $this->input->post('nik'),
					'nama' => $this->input->post('nama'),
					'jk' => $this->input->post('jk'),
					'npwp' => $this->input->post('npwp'),
					'pendidikan' => $this->input->post('pendidikan'),
					'gapok' => $this->input->post('gapok'),
					'tmp_lahir' => $this->input->post('tmp_lahir'),
					'tgl_lahir' => $this->input->post('tgl_lahir'),
					'alamat' => $this->input->post('alamat'),
					'kota' => $this->input->post('kota'),
					'mulai_kerja' => $this->input->post('mulai_kerja'),
					'ms_kerja' => $this->input->post('ms_kerja'),
					'indexins' => $this->input->post('indexins'),
					'bpd' => $this->input->post('bpd'),
					'rekening' => $this->input->post('rekening'),
					'stts_aktif' => $this->input->post('stts_aktif'),
					'wajibmasuk' => $this->input->post('wajibmasuk'),
					'pengurang' => $this->input->post('pengurang'),
					'indek' => $this->input->post('indek'),
					'mulai_kontrak' => $this->input->post('mulai_kontrak'),
					'cuti_diambil' => $this->input->post('cuti_diambil'),
					'dankes' => $this->input->post('dankes'),
					'photo' => $this->input->post('photo'),
					'no_ktp' => $this->input->post('no_ktp'),
                );

                $this->Pegawai_model->update_pegawai($id_pegawai,$params);            
                redirect('pegawai/index');
            }
            else
            {
				$this->load->model('Jabatan_model');
				$data['all_jabatan'] = $this->Jabatan_model->get_all_jabatan();

				$this->load->model('Jnj_jabatan_model');
				$data['all_jnj_jabatan'] = $this->Jnj_jabatan_model->get_all_jnj_jabatan();

				$this->load->model('Departeman_model');
				$data['all_departemen'] = $this->Departeman_model->get_all_departemen();

				$this->load->model('Bidang_model');
				$data['all_bidang'] = $this->Bidang_model->get_all_bidang();

				$data['_view'] = 'pegawai/edit';
				
				$data['title']="Edit Pegawai";
				$data['page']="editpegawai";
				$this->renderAdmin($data);
            }
        }
        else
            show_error('The pegawai you are trying to edit does not exist.');
    } 

    /*
     * Deleting pegawai
     */
    function remove($id_pegawai)
    {
        $pegawai = $this->Pegawai_model->get_pegawai($id_pegawai);

        // check if the pegawai exists before trying to delete it
        if(isset($pegawai['id_pegawai']))
        {
            $this->Pegawai_model->delete_pegawai($id_pegawai);
            redirect('pegawai/index');
        }
        else
            show_error('The pegawai you are trying to delete does not exist.');
	}

	public function renderAdmin($data){
        $this->load->view('layouts/header', $data); 
        $this->load->view('layouts/sidebar' );
        $this->load->view('layouts/maincontent');
        $this->load->view('layouts/footer');
      }
    
}
