<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pendidikan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pendidikan_model');
    } 

    /*
     * Listing of pendidikan
     */
    function index()
    {
        $data['pendidikan'] = $this->Pendidikan_model->get_all_pendidikan();
        
        $data['_view'] = 'pendidikan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pendidikan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tingkat' => $this->input->post('tingkat'),
				'indek' => $this->input->post('indek'),
				'gapok1' => $this->input->post('gapok1'),
				'kenaikan' => $this->input->post('kenaikan'),
				'maksimal' => $this->input->post('maksimal'),
            );
            
            $pendidikan_id = $this->Pendidikan_model->add_pendidikan($params);
            redirect('pendidikan/index');
        }
        else
        {            
            $data['_view'] = 'pendidikan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pendidikan
     */
    function edit($id_pendidikan)
    {   
        // check if the pendidikan exists before trying to edit it
        $data['pendidikan'] = $this->Pendidikan_model->get_pendidikan($id_pendidikan);
        
        if(isset($data['pendidikan']['id_pendidikan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tingkat' => $this->input->post('tingkat'),
					'indek' => $this->input->post('indek'),
					'gapok1' => $this->input->post('gapok1'),
					'kenaikan' => $this->input->post('kenaikan'),
					'maksimal' => $this->input->post('maksimal'),
                );

                $this->Pendidikan_model->update_pendidikan($id_pendidikan,$params);            
                redirect('pendidikan/index');
            }
            else
            {
                $data['_view'] = 'pendidikan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pendidikan you are trying to edit does not exist.');
    } 

    /*
     * Deleting pendidikan
     */
    function remove($id_pendidikan)
    {
        $pendidikan = $this->Pendidikan_model->get_pendidikan($id_pendidikan);

        // check if the pendidikan exists before trying to delete it
        if(isset($pendidikan['id_pendidikan']))
        {
            $this->Pendidikan_model->delete_pendidikan($id_pendidikan);
            redirect('pendidikan/index');
        }
        else
            show_error('The pendidikan you are trying to delete does not exist.');
    }
    
}
