<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stts_kerja extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Stts_kerja_model');
    } 

    /*
     * Listing of stts_kerja
     */
    function index()
    {
        $data['stts_kerja'] = $this->Stts_kerja_model->get_all_stts_kerja();
        
        $data['_view'] = 'stts_kerja/index';
        $this->load->view('layouts/main',$data);
    }

    

    /*
     * Adding a new stts_kerja
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'stts' => $this->input->post('stts'),
				'ktg' => $this->input->post('ktg'),
				'indek' => $this->input->post('indek'),
            );
            
            $stts_kerja_id = $this->Stts_kerja_model->add_stts_kerja($params);
            redirect('stts_kerja/index');
        }
        else
        {            
            $data['_view'] = 'stts_kerja/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a stts_kerja
     */
    function edit($id_sttskerja)
    {   
        // check if the stts_kerja exists before trying to edit it
        $data['stts_kerja'] = $this->Stts_kerja_model->get_stts_kerja($id_sttskerja);
        
        if(isset($data['stts_kerja']['id_sttskerja']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'stts' => $this->input->post('stts'),
					'ktg' => $this->input->post('ktg'),
					'indek' => $this->input->post('indek'),
                );

                $this->Stts_kerja_model->update_stts_kerja($id_sttskerja,$params);            
                redirect('stts_kerja/index');
            }
            else
            {
                $data['_view'] = 'stts_kerja/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The stts_kerja you are trying to edit does not exist.');
    } 

    /*
     * Deleting stts_kerja
     */
    function remove($id_sttskerja)
    {
        $stts_kerja = $this->Stts_kerja_model->get_stts_kerja($id_sttskerja);

        // check if the stts_kerja exists before trying to delete it
        if(isset($stts_kerja['id_sttskerja']))
        {
            $this->Stts_kerja_model->delete_stts_kerja($id_sttskerja);
            redirect('stts_kerja/index');
        }
        else
            show_error('The stts_kerja you are trying to delete does not exist.');
    }
    
}
