<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Departeman_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get departeman by id_departemen
     */
    function get_departeman($id_departemen)
    {
        return $this->db->get_where('departemen',array('id_departemen'=>$id_departemen))->row_array();
    }
        
    /*
     * Get all departemen
     */
    function get_all_departemen()
    {
        $this->db->order_by('id_departemen', 'desc');
        return $this->db->get('departemen')->result_array();
    }
        
    /*
     * function to add new departeman
     */
    function add_departeman($params)
    {
        $this->db->insert('departemen',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update departeman
     */
    function update_departeman($id_departemen,$params)
    {
        $this->db->where('id_departemen',$id_departemen);
        return $this->db->update('departemen',$params);
    }
    
    /*
     * function to delete departeman
     */
    function delete_departeman($id_departemen)
    {
        return $this->db->delete('departemen',array('id_departemen'=>$id_departemen));
    }
}
