<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pendidikan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pendidikan by id_pendidikan
     */
    function get_pendidikan($id_pendidikan)
    {
        return $this->db->get_where('pendidikan',array('id_pendidikan'=>$id_pendidikan))->row_array();
    }
        
    /*
     * Get all pendidikan
     */
    function get_all_pendidikan()
    {
        $this->db->order_by('id_pendidikan', 'desc');
        return $this->db->get('pendidikan')->result_array();
    }
        
    /*
     * function to add new pendidikan
     */
    function add_pendidikan($params)
    {
        $this->db->insert('pendidikan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pendidikan
     */
    function update_pendidikan($id_pendidikan,$params)
    {
        $this->db->where('id_pendidikan',$id_pendidikan);
        return $this->db->update('pendidikan',$params);
    }
    
    /*
     * function to delete pendidikan
     */
    function delete_pendidikan($id_pendidikan)
    {
        return $this->db->delete('pendidikan',array('id_pendidikan'=>$id_pendidikan));
    }
}
