<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stts_kerja_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get stts_kerja by id_sttskerja
     */
    function get_stts_kerja($id_sttskerja)
    {
        return $this->db->get_where('stts_kerja',array('id_sttskerja'=>$id_sttskerja))->row_array();
    }
        
    /*
     * Get all stts_kerja
     */
    function get_all_stts_kerja()
    {
        $this->db->order_by('id_sttskerja', 'desc');
        return $this->db->get('stts_kerja')->result_array();
    }
        
    /*
     * function to add new stts_kerja
     */
    function add_stts_kerja($params)
    {
        $this->db->insert('stts_kerja',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update stts_kerja
     */
    function update_stts_kerja($id_sttskerja,$params)
    {
        $this->db->where('id_sttskerja',$id_sttskerja);
        return $this->db->update('stts_kerja',$params);
    }
    
    /*
     * function to delete stts_kerja
     */
    function delete_stts_kerja($id_sttskerja)
    {
        return $this->db->delete('stts_kerja',array('id_sttskerja'=>$id_sttskerja));
    }
}
